versat/cntlm

Makefile
auth.c
auth.h
configure
debian/control
doc/cntlm.1
forward.c
kerberos.c
kerberos.h
main.c

This is the patch from here https://sourceforge.net/p/cntlm/feature-requests/30/ rebased against your tree.
I've tested it on RHEL7, it builds with and without `--enable-kerberos` and Kerberos functionality works.
I'm creating a PR here, because this seems to be the only spot with active Cntlm develop going on. Please let me know if you are not interested in PRs like these.

Kerberos Proxy authentication, use cached credentials for authentication with the 'parent' proxy

---

main.c

Unfortunately I made a very silly mistake when making PAC support optional.
The ifdef should be below the inclusion of the config.h header.
This PR solves my mistake.

Correct the ordering of the headers so that the pacparser.h header is included when configured.

---

Makefile
configure

Hello, I'm not sure if you (or anyone) is an authoritative maintainer of CNTLM at this point- but your fork was the most up to date one I could find. If you're interested, I added an `--enable-static` flag to `configure` file as well as the `Makefile`
I'm using this branch with a musl-libc toolchain to statically link cntlm with libpacparser support. It's a bigger file of course but doesn't require any dependencies (or require any specific versions of any dependencies) which is useful in my environment
Thanks
(You'll see I also removed an orphaned, commented out debug symbols flag line, the debug symbols are set higher up in the file in a proper conditional block so it seems it's just old clutter)

Add option for static linking via --enable-static

---

main.c

When pacparser is not initialized, _pac_parser_find_proxy()_ is uselessly called in _proxy_thread()_ causing a lot of warning `pacparser.c: pacparser_find_proxy: Pac parser is not initialized.`. This PR surrounds these calls in "if (pacparser_initialized)" blocks. This addresses issue #29.

do not call pacparser_find_proxy if pacparser is not initialized

---

.github/workflows/macos_build.yml
.gitignore
Makefile
Makefile.clang
Makefile.ikos-scan-cc
config/strlcat.c
config/strlcpy.c
configure
utils.c
utils.h

PR #40 solves the issue of compiling on macOS, but only for the basic version of _cntlm_. When you add support for _pacaparser_ (`--enable-pacparser`) the compiler cannot find the `strsep()` standard function.
This can be fixed by setting the macro `_DARWIN_C_SOURCE` which tells the compiler to support Darwin extensions (by default the namespace is set to the same as `_POSIX_C_SOURCE`).
The problem is that this macro puts in scope also `strlcat()`and `strlcpy()`, the BSD functions that are defined in `utils.h` and `utils.c`. This raises another compilation error due to a conflict of these double definitions.
My solution is to make the custom implementation of `strlcat()`and `strlcpy()` optional, based on the availability on the target platform, in a similar way it is done for `strdup()` …

improve macos support

---

main.c

It fixes issue #28 
GSS was initialised in parent process and then used in child process. This caused crash of cntlm process during first attempt to get kerberos token. 
This fix simply moves gss initialisation code after fork()

fix gss crash when running in background mode

---

main.c

This PR fixes an issue that affects cntlm when built with `--enable-kerberos`.
In this scenario the `-a ntlm | nt | lm | gss` option specified by user is defaulted to `gss` every time a kerberos ticket is available.
So when user specifies NTLM authentication:
```
$ cntlm -a ntlm -c cntlm.conf
```
GSS is instead forced during initialisation ! This is not what user wants.
This simple patch restores expected behaviour.

Initialise GSS only when GSS authentication is used

---

main.c
utils.h

253 is the maximum length of a host (domain) name + 6 characters for the port = 259 characters now

fix: Correct the maximum length for host names (259 instead of 49)

---

direct.c
forward.c
kerberos.c
kerberos.h
main.c
socket.c
utils.h

Hello, commit 084d75ba accidentally removed _syslog_ debug messages of incoming connections. This, among other things, made the "-q" command line argument useless.
I need to activate _syslogs_ of connections for debugging purposes, so this PR solves this.
The option "-q" (that now does not need an additional parameter) sets the _syslog_ log level to `LOG_DEBUG` otherwise the default is `LOG_INFO`.
```
if (syslog_debug) {
setlogmask(LOG_UPTO(LOG_DEBUG));
} else {
setlogmask(LOG_UPTO(LOG_INFO));
}
```
Also, all loggings activated by the `debug` flag are `printf` since those are needed for tracing purposes. So that _syslogs_ are for normal executions and _printf_ are for tracing/debugging executions.
Finally, kerberos can be very verbose logging as errors non blocking problems. I changed …

Improve syslog debug logging

---

kerberos.c

After a second thought, it's easy to implement display_name() such that to avoid the vulnerability alert and also the extra allocation, as you noticed in #50.

better implementation of display_name() that avoids vulnerability alert

---

main.c

Threads can be created as detached instead of joinable because we don't need to get their return value when they terminate.
Socks5 threads did not put themselves in the list of joinable threads so they were never joined anyway.
Now detached threads put themselves in the list of terminated threads only for monitoring, so that cntlm when receives a sigterm signal can decide to exit or waiting for pending thread ti finish.
The _serialize_ flag ("-s", only used for debugging) was used only for `proxy_thread` but not for `socks5_thread` and `tunnel_thread`. Now it is checked on all cases.
This PR fixes #49, because `pthread_join()` must not be called on detached threads.
Maybe it can be useful for #18 (@jschwartzenberg can you do some tests?) and maybe also for #3.
I tested both _proxy_ and …

create pthreads as detached instead of joinable

---

main.c

When cntlm starts (e.g. as a Windows service) the computer can still be offline. Cntlm tries to resolve parent proxys' addresses and fails, so it exits with error.
It is not necessary to resolve proxys at startup, but only on demand. This was the behaviour until commit 084d75ba.
With this PR it only checks that the format is correct (i.d. it checks only that a port is defined).

do not resolve parent proxys at startup

---

config.c
forward.c
http.c
kerberos.c
main.c
utils.c
utils.h

This PR improves various stuff.
- fix a memory leak in pac parser logic where `addrinfo` structures were net freed with `freeaddrinfo()` when freeing the list of proxy data
- kerberos logic can log non blocking errors very often, that are not very useful in normal execution, so it's better to log them in verbose (aka debug) mode. So we can also avoid the boilerplate required to prepare the gss log message;
- finally, some fixes to remove many compiler warnings
These commits represent different units of work so it should be better not to squash them.

Improvements

---

Makefile
Makefile.clang
Makefile.ikos-scan-cc
win/setup.iss.in

Cygwin version of cntlm can be simplified since only _cygwin1.dll_ is linked to the exe.
In this way the windows package is cleaner and smaller.
We should find a way to add the _pacparser.dll_ library in case of pacparser support.
Instead kerberos support is not relevant, because imo it doesn't work since it is not built against windows native gssapi libraries (e.g. it tries to find the cached credentials file under /tmp). Anyway there is sspi that does the job...

only cygwin1.dll is required as dependency

---

http.c

Documentation states this:
```
-B    (NTLMToBasic)
This option enables "NTLM-to-basic", which allows you to use one cntlm for multiple users. Please note that all security of NTLM is lost this
way. Basic auth uses just a simple encoding algorithm to "hide" your credentials and it is moderately easy to sniff them.
IMPORTANT: HTTP protocol obviously has means to negotiate authorization before letting you through, but TCP/IP doesn't (i.e. open port is
open port). If you use NTLM-to-basic and DON'T specify some username/password in the configuration file, you are bound to loose tunneling
features, because cntlm alone won't know your credentials.
Because NTLM identification has at least three parts (username, password, domain) and the basic authentication provides fields for only two …
```

keep default domain if not passed during basic authentication

---

Makefile
Makefile.clang
configure

Commit 59113983 revealed to me that on macOS (monterey) `/usr/bin/gcc` is actually `/usr/bin/clang` and clang doesn't have the option `-dumpfullversion` (there's only `-dumpversion`). Also, many `-W` options are different in clang.
Swapping gcc and clang in `configure` solves the issue by selecting the clang Makefile on macOS. On systems where only gcc is present the behaviour is unchanged.
In the Makefile (gcc) I tried to improve readability by isolating the command to extract the gcc version.

Prefer clang over gcc in configure, and clean makefiles

---

Makefile
Makefile.clang
Makefile.ikos-scan-cc
Makefile.xlc
acl.c
acl.h
debian/control
doc/cntlm.1
doc/cntlm.conf
main.c
rpm/cntlm.spec
socket.c
utils.h

This PR restores ACL support that was removed in commit 084d75ba.
The original behaviour is restored, that is ACL rules can be applied only to IPv4 addresses. IPv6 addresses are not yet supported.
This feature is useful in Gateway mode, when clients from the network can connect to _cntlm_.
Since only IPv4 addresses can be configured, IPv6 listening sockets are configured to accept connections only from IPv6 addresses and not from IPv4-mapped IPv6 addresses.

Restore ACL support

---

main.c
sspi.c
sspi.h

_Pacparser_ resources are cleaned too early, that is when the first _sigterm_ signal is received. But _cntlm_ can still serve requests, so _pacparser_ is still needed. This PR moves the clean up at the very end of the execution.
Also, _sspi_ resources (Windows only) were not freed, causing another leak. This PR fixes this.

Free resources of pacparser and sspi on shutdown

---

main.c

Current Kerberos implementation falls back to NTLMv2 authentication but, since NTLMv2 is disabled when Kerberos is chosen, it always fails even if credentials are provided in the configuration file.
This PR keeps NTLMv2 enabled (as default) when Kerberos is chosen.
I have a scenario when some proxies accept kerberos but one accepts only ntlm.

Fallback to ntlmv2 when kerberos authentication fails

---

direct.c

This is a fix for issue #77. Cntlm [advertises](http://cntlm.sourceforge.net/) to be able to authenticate with NTLM against web servers. This works unless the request that needs authentication has a body (e.g. a POST request). In this case the body should be cached so that it could be sent again when the authentication sequence is completed, but Cntlm doesn't cache it, it simply reads data from the client socket and writes it to the server socket.
This use case is probably very rare nowadays, since usually connections use SSL (i.e. https) and Cntlm simply tunnels them.
So adding the logic to deal with plain http connections that require ntlm authentication and have a body in the request (that is, cache the body of the first request) isn't worth the effort.
Instead of removing the feature …

do not attempt authentication to target server when request has a body

---

direct.c

fixes #85.
- added constant BODY_VANISHED with this special meaning of "was not empty, but is now"
- http_body_drop() gets aware of BODY_VANISHED
- direct_request(): set BODY_VANISHED when closing and reopening
Not totally sure if this is the cleanest way to resolve it (maybe having a negative const for a length is a worst practice, maybe the BODY_VANISHED could have been detected more generally in `http_has_body()` than in the specialized `http_body_drop()`.

direct: do not try to read 401 body after a Connection: close

---

forward.c
main.c

I was running into issues with connections that were reaching CNTLM via SOCKS. First of all it would try to use a proxy server whereas according to the PAC file there would be a direct connection. It seems that specifying `/` as the URL was not what the rest of the code was expecting. I saw that other code was passing the hostname or IP address instead plus the port number and the hostname or IP address without a port number. Once I changed that,, connections were made correctly directly.
I also saw problems due to the incomplete `data1` structure after the code was passing through `prepare_http_connect`, so I added the hostname and port number to it. This can result in a segfault later on as the data is expected to be there.
With these fixes in place CNTLM is not crashing anymore and …

Resolve problems connectings coming in via SOCKS

---

Makefile.clang
kerberos.c
kerberos.h
proxy.c

This patch checks whether the returned Kerberos token, encoded in base64, fits the available buffer. If it is larger, the buffer is reallocated with the required dimension.
This patch was circulating for a few years and was recently proposed here by @bas524. I just cleaned it up a bit and made the reallocation conditional only when it is necessary to expand the buffer.
In the meantime, for the macos version, I replaced the deprecated `gssapi` apis with the `GSS framework` and removed some deprecated code.

manage large Kerberos tokens

---

http.c
main.c
utils.c
utils.h

This PR updates the password buffer size to support up to 256 character passwords (the maximum supported by Microsoft in any known NTLM implementation) as well as addresses the following 2 issues:
- Hashes as generated and consumed have all bits complemented (making such disagree with all other NTHash implementations such as passlib). Therefore, this PR corrects this behavior however **will require users using a pre-hashed password in config to recompute the hash**.
- Passwords remain in memory (per the referenced FIXME) even when no longer necessary; this change adds an explicit memory barrier after the memset to zero on the password buffer in an event to prevent the compiler from optimizing away the memset.

Support for up to 256c passphrases, correct bitwise inversion in hashes

---

.github/workflows/c-cpp.yml
.github/workflows/macos_build.yml
.gitignore
Makefile
auth.c
auth.h
config/gss.c
configure
main.c
proxy.c

This PR is for removing the optional parameter "--enable-kerberos" when launching "./configure". Now it can automatically check the existence of GSS header files and shared libraries and activate the compiler directive accordingly.
This also simplifies the CI workflows.

automatically check availability of gss at build time

---

.gitignore
Makefile
config/memset_s.c
configure
http.c
ntlm.c
utils.c

Following the design of cntlm, checked the availability of memset_s in `configure`.
Also correctly clear password buffers as explained in issue #105

use memset_s from standard library if available

---

.github/workflows/c-cpp.yml
.github/workflows/coverity.yml
.github/workflows/macos_build.yml
.github/workflows/sonarcloud.yml
appveyor.yml

For `c-cpp.yml` it is faster to have one job that compiles first with gcc and then with clang. In scan-build we can exclude duktape because it is third party.
`UNICODE` is relevant only for Cygwin because it is used only in sspi.c.
Finally, we can analyse also kerberos code by installing the developer package during setup.

Reorganise some workflows

---

.github/workflows/sonarcloud.yml
sonar-project.properties

The SonarCloud action doesn't work on external PR, that is, PR coming from forks. For security reason the Sonar token is not passed to the action in this case.
This PR injects the organization in the sonar parameters, so that this action can be executed directly in forks.
It also simplifies the implementation, based on SonarCloud documentation.

Ensure the SonarCloud action works independently of the organization
